#!/bin/bash

function getTests() {
    ls *Test.java| while read i; do
        echo -n "`basename $i .java` ";

    done
}
export CLASSPATH=junit-4.10.jar:$CLASSPATH

rm *.class
javac *.java -Xlint:unchecked && java org.junit.runner.JUnitCore `getTests`

